"""update table pupil

Revision ID: 82444e2e8ffc
Revises: e2cf6404802b
Create Date: 2025-10-03 12:25:01.424038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '82444e2e8ffc'
down_revision: Union[str, Sequence[str], None] = 'e2cf6404802b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pupils', 'class_number',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('pupils', 'class_letter',
               existing_type=postgresql.ENUM('A', 'Б', 'В', 'Г', name='classletter'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('pupils', 'class_letter',
               existing_type=postgresql.ENUM('A', 'Б', 'В', 'Г', name='classletter'),
               nullable=False)
    op.alter_column('pupils', 'class_number',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
